export const  GET_ALL_DOGS = "GET_ALL_DOGS";
export const  GET_BY_NAME = "GET_BY_NAME";
export const  GET_DETAIL_BY_ID = "GET_DETAIL_BY_ID";
export const  GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const  FILTERED_BY_TEMP = "FILTERED_BY_TEMP";
export const  FILTERED_BY_ORIGIN = "FILTERED_BY_ORIGIN";
export const  ORDER_ALPHABETICAL = "ORDER_ALPHABETICAL";
export const  ORDER_WEIGHT = "ORDER_WEIGHT";